name: Boldkhuu.com CI

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
    - name: Build the project
      run: pnpm build
    - name: 'Deploy to Azure App Service'
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'boldkhuu'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
